package me.bechberger.ebpf.bpf;

import me.bechberger.ebpf.annotations.bpf.*;
import me.bechberger.ebpf.annotations.bpf.Properties;
import me.bechberger.ebpf.bpf.map.*;
import me.bechberger.ebpf.bpf.map.BPFRingBuffer.BPFRingBufferError;
import me.bechberger.ebpf.bpf.processor.Processor;
import me.bechberger.ebpf.bpf.raw.*;
import me.bechberger.ebpf.shared.KernelFeatures;
import me.bechberger.ebpf.shared.LibC;
import me.bechberger.ebpf.type.BPFType;
import me.bechberger.ebpf.shared.PanamaUtil;
import me.bechberger.ebpf.shared.PanamaUtil.HandlerWithErrno;
import me.bechberger.ebpf.shared.TraceLog;
import me.bechberger.ebpf.shared.TraceLog.TraceFields;
import me.bechberger.ebpf.type.BPFType.BPFStructType;
import me.bechberger.ebpf.type.BPFType.BPFUnionType;
import me.bechberger.ebpf.type.Union;
import org.jetbrains.annotations.Nullable;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.io.OutputStream;
import java.lang.annotation.Annotation;
import java.lang.foreign.Arena;
import java.net.InetSocketAddress;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.StructLayout;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Function;
import java.util.stream.IntStream;

import static java.lang.foreign.ValueLayout.JAVA_BOOLEAN;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
import static me.bechberger.ebpf.NameUtil.toConstantCase;
import static me.bechberger.ebpf.bpf.raw.Lib.*;

/**
 * Base class for bpf programs.
 * <p></p>
 * {@snippet :
 *     @BPF
 *     public static abstract class HelloWorldProgram extends BPFProgram {
 *
 *         static final String EBPF_PROGRAM = """
 *                 #include "vmlinux.h"
 *                 #include <bpf/bpf_helpers.h>
 *                 #include <bpf/bpf_tracing.h>
 *
 *                 SEC ("kprobe/do_sys_openat2") int kprobe__do_sys_openat2 (struct pt_regs *ctx){
 *                     bpf_printk("Hello, World from BPF and more!");
 *                     return 0;
 *                 }
 *
 *                 char _license[] SEC ("license") = "GPL";
 *                 """;
 *     }
 *
 *     public static void main(String[] args) {
 *         try (HelloWorldProgram program = new HelloWorldProgramImpl()) {
 *             program.autoAttachProgram(program.getProgramByName("kprobe__do_sys_openat2"));
 *             program.tracePrintLoop();
 *         }
 *     }
 *}
 */
public abstract class BPFProgram implements AutoCloseable {

    static {
        LibraryLoader.load();
        // set rlimit to allow for more maps
        LibC.setRlimitMemlockToInfinity();
    }

    /**
     * Thrown whenever the whole bpf program could not be loaded
     */
    public static class BPFLoadError extends BPFError {

        public BPFLoadError(String message) {
            super(message);
        }
    }

    /** Get the class generated by the annotation processor for a giving subclass of {@link BPFProgram} */
    @SuppressWarnings("unchecked")
    public static <T, S extends T> Class<S> getImplClass(Class<T> clazz) {
        try {
            var implName = Processor.classToImplName(clazz);
            return (Class<S>) Class.forName(implName.fullyQualifiedClassName());
        } catch (ClassNotFoundException e) {
            throw new BPFError("Implementation class not found, you probably forgot to annotate the " + clazz.getSimpleName() + " class with @BPF", e);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Returns the C code for the given BPFProgram subclass
     */
    public static <T extends BPFProgram> String getCode(Class<T> clazz) {
        try {
            return getImplClass(clazz).getMethod("getCodeStatic").invoke(null).toString();
        } catch (IllegalAccessException | InvocationTargetException | NoSuchMethodException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Prints the generated C code for {@code clazz} to stdout and returns without loading.
     *
     * <p>Useful for inspecting what the compiler plugin generated without running as root.
     * Equivalent to setting the environment variable {@code BPF_PRINT_CODE=1} before calling
     * {@link #load(Class)}.
     *
     * <pre>{@code
     * // From your IDE / unit test — no root required:
     * BPFProgram.printCode(MinimalScheduler.class);
     * }</pre>
     */
    public static <T extends BPFProgram> void printCode(Class<T> clazz) {
        System.out.println("=== BPF C code for " + clazz.getSimpleName() + " ===");
        System.out.println(getCode(clazz));
    }

    /**
     * Loads the implementation class of the given abstract BPFProgram subclass
     * <p>
     * Example: {@snippet :
     *    HelloWorld program = BPFProgram.load(HelloWorld.class);
     *}
     *
     * @param clazz abstract BPFProgram subclass
     * @param <T>   the abstract BPFProgram subclass
     * @param <S>   the implementation class
     * @return instance of the implementation class, created using the default constructor
     */
    public static <T extends BPFProgram, S extends T> S load(Class<T> clazz) {
        try {
            if ("1".equals(System.getenv("BPF_PRINT_CODE"))) {
                printCode(clazz);
            }
            KernelFeatures.requireMinimumKernel();
            KernelFeatures.checkRequirements("Loading BPF program", clazz);
            long t0 = System.currentTimeMillis();
            var program = BPFProgram.<T, S>getImplClass(clazz).getConstructor().newInstance();
            program.initGlobals();
            var evt = new BPFEvents.ProgramLoad();
            if (evt.isEnabled()) {
                evt.programClass = clazz.getName();
                evt.durationMs = System.currentTimeMillis() - t0;
                evt.commit();
            }
            System.Logger logger = System.getLogger(BPFProgram.class.getName());
            if (logger.isLoggable(System.Logger.Level.DEBUG)) {
                logger.log(System.Logger.Level.DEBUG,
                        "Loaded {0}: byteCodeHash={1}", clazz.getSimpleName(), program.byteCodeHash());
            }
            return program;
        } catch (BPFError e) {
            throw e;
        } catch (InvocationTargetException e) {
            // Constructor.newInstance() wraps user-thrown exceptions; unwrap so
            // BPFLoadError / BPFVerifierException propagate to the caller as-is.
            Throwable cause = e.getCause();
            if (cause instanceof BPFError be) {
                throw be;
            }
            throw new RuntimeException(cause != null ? cause : e);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Load a BPF program that depends on already-loaded producer programs.
     *
     * <p>Used with {@code @SharedFrom}: the consumer's generated impl class has a
     * constructor taking the producers it shares maps with. This method picks the
     * matching constructor by parameter assignability and registers the consumer
     * as a dependent on each producer (so producer close fails fast while the
     * consumer is alive).
     *
     * <p>Usage:
     * <pre>{@code
     * try (var producer = BPFProgram.load(Producer.class);
     *      var consumer = BPFProgram.load(Consumer.class, producer)) { ... }
     * // try-with-resources closes consumer first (LIFO), then producer.
     * }</pre>
     *
     * @param clazz     the consumer @BPF class
     * @param producers producer instances the consumer's @SharedFrom fields reference
     * @return the loaded consumer program
     */
    public static <T extends BPFProgram, S extends T> S load(Class<T> clazz, BPFProgram... producers) {
        if (producers == null || producers.length == 0) {
            return load(clazz);
        }
        try {
            if ("1".equals(System.getenv("BPF_PRINT_CODE"))) {
                printCode(clazz);
            }
            KernelFeatures.requireMinimumKernel();
            KernelFeatures.checkRequirements("Loading BPF program", clazz);
            long t0 = System.currentTimeMillis();
            Class<S> implClass = BPFProgram.<T, S>getImplClass(clazz);
            // Find a constructor whose parameter list is assignable from the supplied
            // producers (in order). If multiple match, prefer the one whose parameter
            // count equals the number of producers.
            java.lang.reflect.Constructor<?> chosen = null;
            for (var ctor : implClass.getDeclaredConstructors()) {
                var pTypes = ctor.getParameterTypes();
                if (pTypes.length != producers.length) continue;
                boolean ok = true;
                for (int i = 0; i < pTypes.length; i++) {
                    if (!pTypes[i].isInstance(producers[i])) { ok = false; break; }
                }
                if (ok) { chosen = ctor; break; }
            }
            if (chosen == null) {
                var supplied = new StringBuilder();
                for (int i = 0; i < producers.length; i++) {
                    if (i > 0) supplied.append(", ");
                    supplied.append(producers[i].getClass().getSimpleName());
                }
                throw new BPFLoadError("No constructor on " + implClass.getSimpleName()
                        + " matches the supplied producers (" + supplied + "). "
                        + "Ensure the consumer declares @SharedFrom for each producer "
                        + "and that the producer order matches the generated constructor signature.");
            }
            @SuppressWarnings("unchecked")
            S program = (S) chosen.newInstance((Object[]) producers);
            for (var producer : producers) {
                producer.addDependent(program);
            }
            program.initGlobals();
            var evt = new BPFEvents.ProgramLoad();
            if (evt.isEnabled()) {
                evt.programClass = clazz.getName();
                evt.durationMs = System.currentTimeMillis() - t0;
                evt.commit();
            }
            return program;
        } catch (BPFError e) {
            throw e;
        } catch (InvocationTargetException e) {
            Throwable cause = e.getCause();
            if (cause instanceof BPFError be) throw be;
            throw new RuntimeException(cause != null ? cause : e);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }



    /**
     * The eBPF object, struct bpf_object *ebpf_object
     */
    private final MemorySegment ebpf_object;

    /**
     * Link to an attached program
     */
    public record BPFLink(MemorySegment segment) {}

    private final Set<BPFLink> attachedPrograms = new HashSet<>();
    private final Set<Integer> openedFDs = new HashSet<>();

    private final Set<BPFMap> attachedMaps = new HashSet<>();

    private final Set<MemorySegment> attachedStructOps = new HashSet<>();

    record AttachedXDPIfIndex(int ifindex, int flags) {}

    private final Set<AttachedXDPIfIndex> attachedXDPIfIndexes = new HashSet<>();

    record AttachedTCIfIndex(ProgramHandle handle, int ifindex, boolean ingress, int priority, int tcHandle) {}
    private final Set<AttachedTCIfIndex> attachedTCIfIndices = new HashSet<>();

    private volatile boolean closed = false;

    /**
     * Load the eBPF program from the byte code
     * <p>
     * You have to call {@link #initGlobals()} to initialize the global variables.
     *
     * <h3>Two-phase load (open / finalize split)</h3>
     * The base constructor only <em>opens</em> the BPF object via
     * {@link #openProgram()}; it does <strong>not</strong> call
     * {@code bpf_object__load}. The annotation-processor-generated impl-class
     * constructor calls {@link #finalizeLoad()} after registering any pin
     * paths via {@link #setMapPinPath(String, String)}, so cross-program map
     * sharing (see {@code @SharedFrom}) can wire up before load.
     *
     * <p>For programs without {@code @SharedFrom}, the generated constructor
     * simply calls {@code finalizeLoad()} immediately after {@code super()},
     * preserving the historical "open + load in constructor" behavior.
     */
    public BPFProgram() {
        this.ebpf_object = openProgram();
        // Shutdown hook bypasses the dependent-tracking guard: at JVM shutdown
        // the producer's and consumer's hooks run concurrently, so the producer
        // can't reliably observe the consumer disappearing first. The guard is
        // there to catch programmer errors during normal use; on shutdown we
        // just want the kernel state torn down.
        Runtime.getRuntime().addShutdownHook(new Thread(() -> closeUnchecked()));
    }

    protected void initGlobals() {
    }

    public <T> BPFType<T> getTypeForClass(Class<T> innerType) {
        return getTypeForImplClass(getClass(), innerType);
    }

    public static <T> BPFType<T> getTypeForClass(Class<?> outer, Class<T> inner) {
        return getTypeForImplClass(getImplClass(outer), inner);
    }

    public <T> BPFStructType<T> getStructTypeForClass(Class<T> innerType) {
        return (BPFStructType<T>) getTypeForImplClass(getClass(), innerType);
    }

    public static <T> BPFStructType<T> getStructTypeForClass(Class<?> outer, Class<T> inner) {
        return (BPFStructType<T>) getTypeForImplClass(getImplClass(outer), inner);
    }

    public <T extends Union> BPFUnionType<T> getUnionTypeForClass(Class<T> innerType) {
        return (BPFUnionType<T>) getTypeForImplClass(getClass(), innerType);
    }

    public static <T extends Union> BPFUnionType<T> getUnionTypeForClass(Class<?> outer, Class<T> inner) {
        return (BPFUnionType<T>) getTypeForImplClass(getImplClass(outer), inner);
    }

    private static <T> BPFType<T> getTypeForImplClass(Class<?> outerImpl, Class<T> inner) {
        try {
            return getTypeForImplClass(outerImpl, inner, true);
        } catch (Exception e) {
            return getTypeForImplClass(outerImpl, inner, false);
        }
    }

    @SuppressWarnings("unchecked")
    private static <T> BPFType<T> getTypeForImplClass(Class<?> outerImpl, Class<T> inner, boolean canonical) {
        String fieldName = toConstantCase(canonical ? inner.getCanonicalName() : inner.getSimpleName())
                .replace(".", "__");
        try {
            return (BPFType<T>) outerImpl.getDeclaredField(fieldName).get(null);
        } catch (IllegalAccessException | NoSuchFieldException e) {
            throw new RuntimeException(e);
        }
    }

    private static final HandlerWithErrno<Integer> BPF_OBJECT__LOAD =
            new HandlerWithErrno<>("bpf_object__load",
                    FunctionDescriptor.of(JAVA_INT, PanamaUtil.POINTER));

    private static final HandlerWithErrno<MemorySegment> BPF_OBJECT__OPEN_FILE =
            new HandlerWithErrno<>("bpf_object__open_file",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER, PanamaUtil.POINTER));
    /**
     * Open the eBPF object file (phase 1 of the two-phase load).
     *
     * <p>Calls {@code bpf_object__open_file} but does <strong>not</strong>
     * load the program into the kernel — that is deferred to
     * {@link #finalizeLoad()} so map pin paths can be registered first.
     *
     * @return the opened {@code struct bpf_object *}
     * @throws BPFLoadError if the object file cannot be opened
     */
    private MemorySegment openProgram() {
        VerifierLogCapture.install();
        Path objFile = getTmpObjectFile();
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment fileName = arena.allocateFrom(objFile.toString());

            var ebpf_object = BPF_OBJECT__OPEN_FILE.call(fileName, MemorySegment.NULL);
            if (ebpf_object.result() == MemorySegment.NULL) {
                throw new BPFLoadError("Failed to open eBPF file: " + Util.errnoString(ebpf_object.err()));
            }
            return ebpf_object.result();
        }
    }

    /**
     * Track whether {@link #finalizeLoad()} has been called for this instance.
     * Used to make the call idempotent and to reject post-load operations
     * that require the program to be loaded.
     */
    private boolean loaded = false;

    /**
     * Hook invoked between {@link #openProgram()} and {@link #finalizeLoad()}.
     * Override to register cross-program pin paths via
     * {@link #setMapPinPath(String, String)} before the BPF object is loaded.
     *
     * <p>Default implementation does nothing. The annotation-processor-generated
     * impl-class constructor calls this between {@code super()} and
     * {@code finalizeLoad()}.
     */
    protected void preLoad() {
    }

    /**
     * Finalize the load (phase 2 of the two-phase load): calls
     * {@code bpf_object__load}. Idempotent — calling it twice is a no-op.
     *
     * <p>The annotation-processor-generated impl-class constructor calls this
     * after registering any cross-program pin paths via
     * {@link #setMapPinPath(String, String)}.
     *
     * @throws BPFLoadError if loading fails
     * @throws BPFVerifierException if the BPF verifier rejects the program
     */
    protected final void finalizeLoad() {
        if (loaded) return;
        // discard any prior libbpf chatter so the captured log only contains
        // messages emitted during this bpf_object__load call
        VerifierLogCapture.drainAndReset();
        var ret = BPF_OBJECT__LOAD.call(this.ebpf_object);
        if (ret.hasError() && ret.result() != 0) {
            String shortMsg = "Failed to load eBPF object: " + Util.errnoString(ret.err());
            String log = VerifierLogCapture.drainAndReset();
            if (log.isEmpty()) {
                throw new BPFLoadError(shortMsg);
            }
            throw new BPFVerifierException(shortMsg, log);
        }
        loaded = true;
    }

    /**
     * @return {@code true} once {@link #finalizeLoad()} has succeeded.
     */
    public final boolean isLoaded() {
        return loaded;
    }

    /**
     * Get the names of all functions that represent auto-attachable programs
     * and are defined in C, see {@link #autoAttachPrograms()}.
     * @return the names of the auto-attachable programs
     */
    public abstract List<String> getAutoAttachablePrograms();

    /**
     * All auto-attachable programs, defined in C and in Java.
     * <p>
     * Also includes all methods that are annotated with {@link BPFFunction} and
     * @return names of all auto-attachable programs
     */
    public List<String> getAllAutoAttachablePrograms() {
        // get all methods that are annotated with BPFFunction and where autoAttach is true
        var names = new ArrayList<>(getAutoAttachablePrograms());
        var programClass = getClass().getSuperclass();
        var erroneous = new ArrayList<String>();
        for (var method : programClass.getDeclaredMethods()) {
            var annotation = findParentAnnotation(programClass, method, BPFFunction.class);
            if (annotation != null && annotation.autoAttach()) {
                var baseSection = annotation.section().split("/")[0];
                if (!BPFFunction.autoAttachableSections.contains(baseSection)) {
                    erroneous.add(method.getName() + " with section " + annotation.section());
                    continue;
                }
                names.add(annotation.name().isEmpty() ? method.getName() : annotation.name());
            }
            // Also handle shorthand attach annotations
            var shorthandName = getShorthandAttachName(programClass, method);
            if (shorthandName != null && !names.contains(shorthandName)) {
                names.add(shorthandName);
            }
        }
        if (!erroneous.isEmpty()) {
            throw new BPFError("Auto-attachable sections are: " + BPFFunction.autoAttachableSections +
                    ", but the following methods have invalid sections: " + erroneous);
        }
        return names;
    }

    /**
     * Returns the C function name for a method annotated with a shorthand attach annotation
     * ({@code @Kprobe}, {@code @Fentry}, etc.), or {@code null} if none is present.
     */
    private @Nullable String getShorthandAttachName(Class<?> programClass, Method method) {
        for (var annClass : List.of(
                me.bechberger.ebpf.annotations.bpf.Kprobe.class,
                me.bechberger.ebpf.annotations.bpf.Kretprobe.class,
                me.bechberger.ebpf.annotations.bpf.Fentry.class,
                me.bechberger.ebpf.annotations.bpf.Fexit.class,
                me.bechberger.ebpf.annotations.bpf.RawTracepoint.class,
                me.bechberger.ebpf.annotations.bpf.Ksyscall.class,
                me.bechberger.ebpf.annotations.bpf.Uprobe.class,
                me.bechberger.ebpf.annotations.bpf.Uretprobe.class,
                me.bechberger.ebpf.annotations.bpf.LSM.class)) {
            var ann = findParentAnnotation(programClass, method, annClass);
            if (ann != null) {
                return method.getName();
            }
        }
        // @Tracepoint with two elements
        var tp = findParentAnnotation(programClass, method, me.bechberger.ebpf.annotations.bpf.Tracepoint.class);
        if (tp != null) {
            return method.getName();
        }
        return null;
    }

    public void attachLSMHooks() {
        // Walk the full superclass chain so @LSM hooks declared on intermediate
        // base classes (e.g. user-defined SchedulerBase-style helpers) are picked
        // up, not only those on the immediate parent of the generated impl.
        Class<?> c = getClass().getSuperclass();
        java.util.Set<String> seen = new java.util.HashSet<>();
        while (c != null && c != Object.class && c != BPFProgram.class) {
            for (var method : c.getDeclaredMethods()) {
                String key = method.getName() + "(" + java.util.Arrays.toString(method.getParameterTypes()) + ")";
                if (!seen.add(key)) continue;
                var annotation = findParentAnnotation(c, method, BPFFunction.class);
                boolean isLsmSection = annotation != null && annotation.section().startsWith("lsm/");
                boolean hasLsmAnnotation = findParentAnnotation(c, method,
                        me.bechberger.ebpf.annotations.bpf.LSM.class) != null;
                if (isLsmSection || hasLsmAnnotation) {
                    attachLSMHook(getProgramByName(getBPFFunctionName(method)));
                }
            }
            c = c.getSuperclass();
        }
    }

    private static final HandlerWithErrno<MemorySegment> BPF_PROGRAM__ATTACH_LSM =
            new HandlerWithErrno<>("bpf_program__attach_lsm",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER));

    public void attachLSMHook(ProgramHandle prog) {
        var ret = BPF_PROGRAM__ATTACH_LSM.call(prog.prog());
        if (ret.result() == MemorySegment.NULL) {
            throw new BPFAttachError(prog.name, ret.err());
        }
        var link = new BPFLink(ret.result());
        if (link.segment.address() == 0) {
            throw new BPFAttachError(prog.name, ret.err());
        }
        attachedPrograms.add(link);
    }

    /**
     * Returns {@code true} if BPF LSM is active on this kernel.
     *
     * <p>Reads {@code /sys/kernel/security/lsm} and checks whether {@code bpf}
     * appears in the comma-separated list. Returns {@code false} if the file
     * cannot be read (e.g. securityfs not mounted) or {@code bpf} is absent.
     */
    public static boolean isLSMEnabled() {
        try {
            var lsmList = Files.readString(Path.of("/sys/kernel/security/lsm")).strip();
            for (var module : lsmList.split(",")) {
                if (module.strip().equals("bpf")) return true;
            }
        } catch (IOException ignored) {
        }
        return false;
    }

    private static final HandlerWithErrno<MemorySegment> BPF_PROGRAM__ATTACH_KPROBE =
            new HandlerWithErrno<>("bpf_program__attach_kprobe",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER,
                            JAVA_BOOLEAN, PanamaUtil.POINTER));

    /**
     * Dynamically attach a kprobe (or kretprobe) to a kernel symbol by name.
     *
     * <p>Unlike the declarative {@code @Kprobe} annotation (which resolves the
     * symbol at compile / annotation-processing time), this method accepts a
     * runtime string — useful when the target symbol is configurable by the
     * user at startup.
     *
     * <p>The returned {@link BPFLink} is managed by this program's lifetime:
     * it is automatically destroyed when the program is closed.  To detach
     * early, call {@link #detachProgram(BPFLink)}.
     *
     * @param prog      the BPF program to attach (must have prog_type KPROBE)
     * @param symbol    kernel function name, e.g. {@code "do_sys_openat2"}
     * @param retprobe  {@code true} to attach on function return (kretprobe)
     * @return the link representing the attachment
     * @throws BPFAttachError if libbpf reports an error
     */
    public BPFLink attachKProbe(ProgramHandle prog, String symbol, boolean retprobe) {
        try (Arena arena = Arena.ofConfined()) {
            var ret = BPF_PROGRAM__ATTACH_KPROBE.call(
                    prog.prog(), retprobe, arena.allocateFrom(symbol));
            if (ret.result() == MemorySegment.NULL) {
                throw kprobeAttachError(prog.name, symbol, ret.err());
            }
            var link = new BPFLink(ret.result());
            if (link.segment.address() == 0) {
                throw kprobeAttachError(prog.name, symbol, ret.err());
            }
            attachedPrograms.add(link);
            return link;
        }
    }

    /**
     * Build a {@link BPFAttachError} with a hint when the kernel symbol could
     * not be resolved (libbpf returns ENOENT / EINVAL in that case). The hint
     * checks {@code /proc/kallsyms} so the user immediately sees a typo or a
     * symbol that was renamed/inlined.
     */
    private static BPFAttachError kprobeAttachError(String progName, String symbol, int errno) {
        String hint = "";
        if (errno == 2 /* ENOENT */ || errno == 22 /* EINVAL */) {
            try {
                boolean found = false;
                try (var lines = Files.lines(Path.of("/proc/kallsyms"))) {
                    found = lines.anyMatch(l -> l.endsWith(" " + symbol)
                            || l.contains(" " + symbol + "\t")
                            || l.contains(" " + symbol + " "));
                }
                if (!found) {
                    hint = " (kernel symbol '" + symbol + "' not found in /proc/kallsyms — typo, inlined, or unexported?)";
                }
            } catch (IOException ignored) {
                // /proc/kallsyms not readable (likely kptr_restrict>0 without CAP_SYSLOG)
            }
        }
        return new BPFAttachError(progName + " for symbol '" + symbol + "'" + hint, errno);
    }

    /**
     * Dynamically attach a kprobe to a kernel symbol by name (entry point).
     *
     * <p>Convenience overload of {@link #attachKProbe(ProgramHandle, String, boolean)}
     * with {@code retprobe = false}.
     */
    public BPFLink attachKProbe(ProgramHandle prog, String symbol) {
        return attachKProbe(prog, symbol, false);
    }

    // -----------------------------------------------------------------------
    // uprobe / uretprobe — dynamic attachment to user-space function symbols
    // -----------------------------------------------------------------------

    // bpf_program__attach_uprobe_opts layout (x86-64 LP64):
    //   offset 0  : size_t sz              (8 bytes)
    //   offset 8  : size_t ref_ctr_offset  (8 bytes)
    //   offset 16 : u64    bpf_cookie      (8 bytes)
    //   offset 24 : bool   retprobe        (1 byte, padded to 8 with align)
    //   offset 32 : char * func_name       (8 bytes pointer)
    //   offset 40 : int    attach_mode     (4 bytes)
    //   total padded to 48 bytes (align to 8)
    private static final StructLayout UPROBE_OPTS_LAYOUT = MemoryLayout.structLayout(
            JAVA_LONG.withName("sz"),
            JAVA_LONG.withName("ref_ctr_offset"),
            JAVA_LONG.withName("bpf_cookie"),
            JAVA_BOOLEAN.withName("retprobe"),
            MemoryLayout.paddingLayout(7),
            PanamaUtil.POINTER.withName("func_name"),
            JAVA_INT.withName("attach_mode"),
            MemoryLayout.paddingLayout(4)
    );

    private static final HandlerWithErrno<MemorySegment> BPF_PROGRAM__ATTACH_UPROBE_OPTS =
            new HandlerWithErrno<>("bpf_program__attach_uprobe_opts",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER, JAVA_INT,
                            PanamaUtil.POINTER, JAVA_LONG, PanamaUtil.POINTER));

    /**
     * Dynamically attach a uprobe (or uretprobe) to a user-space function by symbol name.
     *
     * <p>Resolves the symbol within {@code binaryPath} via libbpf's
     * {@code bpf_program__attach_uprobe_opts}, so no manual ELF parsing is required.
     * Pass {@code pid = -1} to trace all processes, or a specific PID to trace only
     * that process.
     *
     * <p>The returned {@link BPFLink} is managed by this program's lifetime and is
     * automatically destroyed when the program is closed.
     *
     * @param prog       the BPF program to attach (must have prog_type KPROBE)
     * @param retprobe   {@code true} to attach on function return (uretprobe)
     * @param pid        process ID to trace ({@code -1} = all processes)
     * @param binaryPath path to the ELF binary, e.g. {@code "/usr/lib/libc.so.6"}
     * @param funcName   function symbol name, e.g. {@code "malloc"}
     * @return the link representing the attachment
     * @throws BPFAttachError if libbpf reports an error
     */
    public BPFLink attachUprobe(ProgramHandle prog, boolean retprobe, int pid,
                                String binaryPath, String funcName) {
        try (Arena arena = Arena.ofConfined()) {
            var opts = arena.allocate(UPROBE_OPTS_LAYOUT);
            opts.set(JAVA_LONG, 0, UPROBE_OPTS_LAYOUT.byteSize());    // sz
            opts.set(JAVA_LONG, 8, 0L);                                // ref_ctr_offset
            opts.set(JAVA_LONG, 16, 0L);                               // bpf_cookie
            opts.set(JAVA_BOOLEAN, 24, retprobe);                      // retprobe
            opts.set(PanamaUtil.POINTER, 32, arena.allocateFrom(funcName)); // func_name
            opts.set(JAVA_INT, 40, 0);                                 // attach_mode = default

            var ret = BPF_PROGRAM__ATTACH_UPROBE_OPTS.call(
                    prog.prog(),
                    pid,
                    arena.allocateFrom(binaryPath),
                    0L,    // func_offset = 0 (resolved via func_name)
                    opts);
            if (ret.result() == MemorySegment.NULL) {
                throw new BPFAttachError(prog.name, ret.err());
            }
            var link = new BPFLink(ret.result());
            if (link.segment.address() == 0) {
                throw new BPFAttachError(prog.name, ret.err());
            }
            attachedPrograms.add(link);
            return link;
        }
    }

    /**
     * Attach a uprobe to the given symbol in {@code binaryPath} for all processes.
     *
     * <p>Convenience overload of
     * {@link #attachUprobe(ProgramHandle, boolean, int, String, String)}
     * with {@code pid = -1} (all processes) and {@code retprobe = false}.
     */
    public BPFLink attachUprobe(ProgramHandle prog, String binaryPath, String funcName) {
        return attachUprobe(prog, false, -1, binaryPath, funcName);
    }

    /**
     * Attach a uretprobe (return probe) to the given symbol in {@code binaryPath}
     * for all processes.
     *
     * <p>Convenience overload of
     * {@link #attachUprobe(ProgramHandle, boolean, int, String, String)}
     * with {@code pid = -1} and {@code retprobe = true}.
     */
    public BPFLink attachUretprobe(ProgramHandle prog, String binaryPath, String funcName) {
        return attachUprobe(prog, true, -1, binaryPath, funcName);
    }

    /**
     * Attach all {@code uprobe} and {@code uretprobe} BPF programs declared on this class
     * to the given binary, optionally scoped to a single process.
     *
     * <p>Scans every method annotated with {@link BPFFunction} whose
     * {@link BPFFunction#section()} starts with {@code "uprobe/"} or
     * {@code "uretprobe/"}.  The symbol name is taken as the part of the section
     * string that follows the prefix (e.g. section {@code "uprobe/malloc"} ↦ symbol
     * {@code "malloc"}).
     *
     * <p>This removes the per-symbol boilerplate from programs that trace many
     * functions in the same binary:
     * <pre>{@code
     * // Instead of:
     * program.attachUprobe(program.getProgramByName("onAlloc"), false, pid, lib, "malloc");
     * program.attachUprobe(program.getProgramByName("onFree"),  false, pid, lib, "free");
     *
     * // Just write:
     * program.attachAllUprobes(pid, "/usr/lib/libc.so.6");
     * }</pre>
     *
     * <p>Methods that use a {@link BPFFunction#name()} override have that name used
     * to look up the {@link ProgramHandle} instead of the Java method name.
     *
     * @param pid        process ID to scope the probes to, or {@code -1} for all processes
     * @param binaryPath path to the ELF binary containing the target symbols
     * @return list of created {@link BPFLink}s (one per matched program)
     * @throws BPFAttachError if any individual symbol attachment fails
     */
    public List<BPFLink> attachAllUprobes(int pid, String binaryPath) {
        List<BPFLink> links = new ArrayList<>();
        for (Method method : getClass().getMethods()) {
            BPFFunction ann = getAnnotationOfSelfOrOverriden(method, BPFFunction.class);
            if (ann == null) continue;
            String section = ann.section();
            boolean isUprobe    = section.startsWith("uprobe/");
            boolean isUretprobe = section.startsWith("uretprobe/");
            if (!isUprobe && !isUretprobe) continue;
            String symbol  = section.substring(section.indexOf('/') + 1);
            String progName = ann.name().isEmpty() ? method.getName() : ann.name();
            ProgramHandle handle = getProgramByName(progName);
            links.add(attachUprobe(handle, isUretprobe, pid, binaryPath, symbol));
        }
        return links;
    }

    private <T extends Annotation> @Nullable T findParentAnnotation(Class<?> programClass, Method method, Class<T> annotationClass) {
        var annotation = method.getAnnotation(annotationClass);
        if (annotation != null) {
            return annotation;
        }
        for (var iface : programClass.getInterfaces()) {
            try {
                var ifaceMethod = iface.getMethod(method.getName(), method.getParameterTypes());
                annotation = ifaceMethod.getAnnotation(annotationClass);
                if (annotation != null) {
                    return annotation;
                } else {
                    return findParentAnnotation(iface, ifaceMethod, annotationClass);
                }
            } catch (NoSuchMethodException ignored) {
                // Method not found in this interface, ignore and continue
            }
        }
        return null;
    }

    /**
     * Get the names of all Java defined functions that represent auto-attachable programs of the passed class.
     * <p>
     * All methods attached with {@link BPFFunction} and {@link BPFFunction#autoAttach()} is true.
     */
    public static List<String> getAutoAttachableBPFPrograms(Class<? extends BPFProgram> clazz) {
        return Arrays.stream(clazz.getMethods()).map(m -> {
                    var ann = getAnnotationOfSelfOrOverriden(m, BPFFunction.class);
                    if (ann != null && ann.autoAttach()) {
                        return ann.name().isEmpty() ? m.getName() : ann.name();
                    }
                    return null;
                })
                .filter(Objects::nonNull).toList();
    }

    private static <T extends Annotation> @Nullable T getAnnotationOfSelfOrOverriden(Method method, Class<T> annotationClass) {
        // Get annotations of the current method
        T annotation = method.getAnnotation(annotationClass);
        if (annotation != null) {
            return annotation;
        }

        // Get annotations from methods in interfaces
        Class<?> declaringClass = method.getDeclaringClass();
        for (Class<?> iface : declaringClass.getInterfaces()) {
            try {
                Method ifaceMethod = iface.getMethod(method.getName(), method.getParameterTypes());
                T ifaceAnnotation = ifaceMethod.getAnnotation(annotationClass);
                if (ifaceAnnotation != null) {
                    return ifaceAnnotation;
                }
            } catch (NoSuchMethodException ignored) {
                // Method not found in this interface, ignore and continue
            }
        }

        return null;
    }

    private static String getBPFFunctionName(Method method) {
        var annotation = getAnnotationOfSelfOrOverriden(method, BPFFunction.class);
        if (annotation == null || annotation.name().isEmpty()) {
            return method.getName();
        }
        return annotation.name();
    }

    /**
     * Get the byte code of the bpf program.
     *
     * @return the byte code
     */
    public abstract byte[] getByteCode();

    /**
     * Get the code of the bpf program.
     *
     * @return the C code
     */
    public abstract String getCode();

    /**
     * Returns the SHA-256 hex digest of the compiled BPF object bytes.
     *
     * <p>Two builds producing the same source should produce the same hash if the toolchain
     * is deterministic. Log this value to detect unintentional toolchain-version drift.
     */
    public String byteCodeHash() {
        try {
            var digest = MessageDigest.getInstance("SHA-256");
            var bytes = digest.digest(getByteCode());
            var sb = new StringBuilder(bytes.length * 2);
            for (byte b : bytes) sb.append(String.format("%02x", b));
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    private Path getTmpObjectFile() {
        try {
            Path tmp = Files.createTempFile("bpf", ".o");
            tmp.toFile().deleteOnExit();
            try (var os = Files.newOutputStream(tmp)) {
                os.write(getByteCode());
            }
            return tmp;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * A handle to an ebpf program (an entry point function in the eBPF program)
     */
    public record ProgramHandle(String name, MemorySegment prog) {
    }

    public static class BPFProgramNotFound extends BPFError {
        public BPFProgramNotFound(String name) {
            super("Program not found: " + name);
        }
    }

    /**
     * Get a program handle by name
     *
     * @param name the name of the program, or null, if the program cannot be found
     * @return the program handle
     * @throws BPFProgramNotFound if the program cannot be found
     */
    public ProgramHandle getProgramByName(String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment prog = Lib.bpf_object__find_program_by_name(this.ebpf_object, arena.allocateFrom(name));
            if (prog == MemorySegment.NULL || prog.address() == 0) {
                throw new BPFProgramNotFound(name);
            }
            return new ProgramHandle(name, prog);
        }
    }

    /**
     * Invoke a {@code SEC("syscall")} BPF program from userspace via {@code BPF_PROG_TEST_RUN}.
     *
     * <p>The program must be declared with {@code @BPFFunction(section = "syscall",
     * headerTemplate = "int BPF_PROG($name, struct ctx *arg)", autoAttach = false)}. The Java
     * {@code ctx} class must be a {@code @Type} struct registered with this BPFProgram.
     * (The parameter name must NOT be {@code ctx} — {@code BPF_PROG} synthesizes its own
     * {@code unsigned long long *ctx}, causing a redefinition.)
     *
     * <p>The ctx struct is serialized into a flat buffer, handed to the kernel as
     * {@code bpf_test_run_opts.ctx_in}, and the buffer (with any kernel-side writes) is parsed
     * back into a fresh {@code T} on success.
     *
     * @param programName the name of the {@code @BPFFunction} (must match the Java method name)
     * @param ctx         the input context
     * @param <T>         the {@code @Type} class of the context struct
     * @return a {@link SyscallResult} carrying the program's {@code int} return value and the
     *         post-call ctx state
     * @throws BPFError if the program is not found, the ctx type is unknown, or the kernel call fails
     */
    public <T> SyscallResult<T> runSyscallProgram(String programName, T ctx) {
        @SuppressWarnings("unchecked")
        Class<T> ctxClass = (Class<T>) ctx.getClass();
        BPFStructType<T> type = getStructTypeForClass(ctxClass);
        ProgramHandle prog = getProgramByName(programName);
        int progFd = Lib_2.bpf_program__fd(prog.prog());
        if (progFd < 0) {
            throw new BPFError("Failed to get fd for syscall program '" + programName + "'", -progFd);
        }
        try (Arena arena = Arena.ofConfined()) {
            long ctxSize = type.size();
            MemorySegment ctxBuf = arena.allocate(ctxSize);
            type.setMemory(ctxBuf, ctx);
            MemorySegment opts = bpf_test_run_opts.allocate(arena);
            bpf_test_run_opts.sz(opts, bpf_test_run_opts.sizeof());
            bpf_test_run_opts.ctx_in(opts, ctxBuf);
            bpf_test_run_opts.ctx_size_in(opts, (int) ctxSize);
            int ret = Lib_2.bpf_prog_test_run_opts(progFd, opts);
            if (ret != 0) {
                throw new BPFError("bpf_prog_test_run_opts failed for '" + programName + "'", -ret);
            }
            T updated = type.parseMemory(ctxBuf);
            return new SyscallResult<>(bpf_test_run_opts.retval(opts), updated);
        }
    }

    /**
     * Result of {@link #runSyscallProgram(String, Object)}: the program's return value and the
     * post-call ctx state.
     */
    public record SyscallResult<T>(int retval, T ctx) {}

    /**
     * Thrown when attaching a specific program / entry function fails
     */
    public static class BPFAttachError extends BPFError {

        private final int error;

        public BPFAttachError(String name, int errorCode) {
            super("Failed to attach " + name, errorCode);
            this.error = errorCode;
        }

        public BPFAttachError(String name, String message) {
            super("Failed to attach " + name + ":" + message);
            this.error = 0;
        }

        public int getErrorCode() {
            return error;
        }
    }

    private static final HandlerWithErrno<MemorySegment> BPF_PROGRAM__ATTACH =
            new HandlerWithErrno<>("bpf_program__attach",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER));

    /**
     * Attach the program by the automatically detected program type, attach type, and extra paremeters, where
     * applicable.
     *
     * @param prog program to attach
     * @throws BPFAttachError when attaching fails
     */
    public BPFLink autoAttachProgram(ProgramHandle prog) {
        var ret = BPF_PROGRAM__ATTACH.call(prog.prog());
        if (ret.result() == MemorySegment.NULL) {
            throw new BPFAttachError(prog.name, ret.err());
        }
        var link = new BPFLink(ret.result());
        if (link.segment.address() == 0) {
            throw new BPFAttachError(prog.name, ret.err());
        }
        attachedPrograms.add(link);
        var evt = new BPFEvents.ProgramAttach();
        if (evt.isEnabled()) {
            evt.programName = prog.name;
            evt.section = prog.name;
            evt.commit();
        }
        return link;
    }

    /**
     * Attach the program by the automatically detected program type, attach type, and extra paremeters, where
     * applicable.
     *
     * @param name name of the program to attach
     * @throws BPFAttachError when attaching fails
     */
    public BPFLink autoAttachProgram(String name) {
        return autoAttachProgram(getProgramByName(name));
    }

    /**
     * Attach all programs by the automatically detected program type, attach type, and extra paremeters, where
     * applicable.
     * <p>
     * Auto-attaches all programs that are prefixed by "SEC(...)" in the eBPF program.
     * It works with
     * <li>
     *     <ul>fentry, fexit of syscalls: e.g. <code>SEC("fentry/do_unlinkat")
     * int BPF_PROG(do_unlinkat, int dfd, struct filename *name)</code>, <code>SEC("fexit/do_unlinkat")
     * int BPF_PROG(do_unlinkat_exit, int dfd, struct filename *name, long ret)</code></ul>
     * </li>
     * See <a href="https://man7.org/linux/man-pages/man2/syscalls.2.html">syscalls(2)</a> for a list of syscalls.
     * @return
     */
    public BPFProgram autoAttachPrograms() {
        var lsmNames = getLSMProgramNames();
        for (var name : getAllAutoAttachablePrograms()) {
            if (lsmNames.contains(name)) {
                attachLSMHook(getProgramByName(name));
            } else {
                autoAttachProgram(name);
            }
        }
        return this;
    }

    /** Returns the C function names of all methods annotated with {@code @LSM} or having an lsm/ section. */
    private java.util.Set<String> getLSMProgramNames() {
        var names = new java.util.HashSet<String>();
        var programClass = getClass().getSuperclass();
        for (var method : programClass.getDeclaredMethods()) {
            var annotation = findParentAnnotation(programClass, method, BPFFunction.class);
            boolean isLsmSection = annotation != null && annotation.section().startsWith("lsm/");
            boolean hasLsmAnnotation = findParentAnnotation(programClass, method,
                    me.bechberger.ebpf.annotations.bpf.LSM.class) != null;
            if (isLsmSection || hasLsmAnnotation) {
                names.add(getBPFFunctionName(method));
            }
        }
        return names;
    }

    private static final HandlerWithErrno<MemorySegment> BPF_PROGRAM__ATTACH_PERF_EVENT =
            new HandlerWithErrno<>("bpf_program__attach_perf_event",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER, JAVA_INT));

    /**
     * Attach a {@code SEC("perf_event")} BPF program to an already-open perf event
     * file descriptor ({@code pfd}).
     *
     * <p>The {@code pfd} is obtained by calling the {@code perf_event_open(2)} syscall.
     * The BPF program fires every time the perf event is triggered (e.g. on each
     * CPU-cycles overflow).  The returned {@link BPFLink} is tracked by this program's
     * lifetime and automatically destroyed when {@link #close()} is called.
     *
     * @param prog the BPF program to attach (must have prog_type PERF_EVENT)
     * @param pfd  an open perf event file descriptor
     * @return the link representing the attachment
     * @throws BPFAttachError if libbpf reports an error
     */
    public BPFLink attachPerfEvent(ProgramHandle prog, int pfd) {
        var ret = BPF_PROGRAM__ATTACH_PERF_EVENT.call(prog.prog(), pfd);
        if (ret.result() == null || MemorySegment.NULL.equals(ret.result()) || ret.result().address() == 0) {
            throw new BPFAttachError(prog.name, ret.err());
        }
        var link = new BPFLink(ret.result());
        attachedPrograms.add(link);
        return link;
    }

    public BPFLink attachPerfEvent(String programName, int pfd) {
        return attachPerfEvent(getProgramByName(programName), pfd);
    }

    private static final HandlerWithErrno<MemorySegment> BPF_PROGRAM__ATTACH_RAW_TRACEPOINT =
            new HandlerWithErrno<>("bpf_program__attach_raw_tracepoint",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER, PanamaUtil.POINTER));

    public BPFLink rawTracepointAttach(String programName, String tracepoint) {
        return rawTracepointAttach(getProgramByName(programName), tracepoint);
    }

    public BPFLink rawTracepointAttach(ProgramHandle prog, String tracepoint) {
        try (var arena = Arena.ofConfined()) {
            var ret = BPF_PROGRAM__ATTACH_RAW_TRACEPOINT.call(prog.prog(), arena.allocateFrom(tracepoint));
            if (ret.result() == MemorySegment.NULL) {
                throw new BPFAttachError(prog.name, ret.err());
            }
            var link = new BPFLink(ret.result());
            if (link.segment.address() == 0) {
                throw new BPFAttachError(prog.name, ret.err());
            }
            attachedPrograms.add(link);
            return link;
        }
    }

    private static final HandlerWithErrno<MemorySegment> BPF_PROGRAM__ATTACH_TRACEPOINT =
            new HandlerWithErrno<>("bpf_program__attach_tracepoint",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER, PanamaUtil.POINTER));

    public BPFLink tracepointAttach(String programName, String tracepoint) {
        return tracepointAttach(getProgramByName(programName), tracepoint);
    }

    public BPFLink tracepointAttach(ProgramHandle prog, String tracepoint) {
        try (var arena = Arena.ofConfined()) {
            var ret = BPF_PROGRAM__ATTACH_TRACEPOINT.call(prog.prog(), arena.allocateFrom(tracepoint));
            if (ret.result() == MemorySegment.NULL) {
                throw new BPFAttachError(prog.name, ret.err());
            }
            var link = new BPFLink(ret.result());
            if (link.segment.address() == 0) {
                throw new BPFAttachError(prog.name, ret.err());
            }
            attachedPrograms.add(link);
            return link;
        }
    }

    public void xdpAttach(ProgramHandle prog, List<Integer> ifindex) {
        for (var index : ifindex) {
            xdpAttach(prog, index);
        }
    }

    public void xdpAttach(ProgramHandle prog, int ifindex) {
        int fd = Lib.bpf_program__fd(prog.prog());
        int flags = NetworkUtil.XDP_FLAGS_UPDATE_IF_NOEXIST;
        int err = Lib.bpf_xdp_attach(ifindex, fd, flags, MemorySegment.NULL);
        if (err != 0) {
            throw new BPFAttachError(prog.name, err);
        }
        attachedXDPIfIndexes.add(new AttachedXDPIfIndex(ifindex, flags));
    }

    public void tcAttach(ProgramHandle prog, List<Integer> ifindex, boolean ingress) {
        for (var index : ifindex) {
            tcAttach(prog, index, ingress);
        }
    }

    public void tcAttach(ProgramHandle prog, int ifindex, boolean ingress) {
        var tcIfIndex = new AttachedTCIfIndex(prog, ifindex, ingress, 0, 0);
        try (var arena = Arena.ofConfined()) {
            MemorySegment hook = allocateTCHookObject(arena, tcIfIndex);
            // run tc qdisc del dev $DEVICE clsact on the command line
            // to remove the clsact qdisc if it exists
            try {
                Runtime.getRuntime().exec(new String[]{"tc", "qdisc", "del", "dev", NetworkUtil.getNetworkInterfaceName(ifindex), "clsact"}).waitFor();
            } catch (IOException | InterruptedException e) {
            }
            hook = allocateTCHookObject(arena, tcIfIndex);
            MemorySegment opts = allocateTCOptsObject(arena, tcIfIndex);
            int err = Lib.bpf_tc_hook_create(hook);
            if (err != 0) {
                throw new BPFAttachError(prog.name, err);
            }
            err = Lib.bpf_tc_attach(hook, opts);
            if (err != 0) {
                throw new BPFAttachError(prog.name, err);
            }
            // bpf_tc_attach writes back the kernel-assigned handle and priority into opts.
            int assignedHandle   = bpf_tc_opts.handle(opts);
            int assignedPriority = bpf_tc_opts.priority(opts);
            attachedTCIfIndices.add(new AttachedTCIfIndex(prog, ifindex, ingress, assignedPriority, assignedHandle));
        }
    }

    /**
     * Find the cgroup path by name
     * @param cgroupName the name of the cgroup
     * @return the path to the cgroup, or null if the cgroup could not be found
     */
    public static @Nullable Path findCGroupPath(String cgroupName) {
        try {
            return Files.list(Path.of("/sys/fs/cgroup")).filter(p -> p.getFileName().toString().equals(cgroupName)).findFirst().orElse(null);
        } catch (IOException e) {
            return null;
        }
    }

    private static final HandlerWithErrno<MemorySegment> BPF_PROGRAM__ATTACH_CGROUP =
            new HandlerWithErrno<>("bpf_program__attach_cgroup",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER, JAVA_INT));

    private void cgroupAttachInternal(ProgramHandle handle, String cgroupName) {
        var cgroupPath = findCGroupPath(cgroupName);
        if (cgroupPath == null) {
            throw new BPFAttachError(handle.name, "Cgroup not found: " + cgroupName);
        }
        PanamaUtil.ResultAndErr<Integer> fileFD = LibC.open(cgroupPath, O_RDONLY());
        if (fileFD.err() > 0) {
            throw new BPFAttachError(handle.name, fileFD.err());
        }
        openedFDs.add(fileFD.result());

        var resultAndErr = BPF_PROGRAM__ATTACH_CGROUP.call(handle.prog, fileFD.result());
        if (resultAndErr.err() > 0) {
            throw new BPFAttachError(handle.name, resultAndErr.err());
        }
        if (resultAndErr.result() == MemorySegment.NULL) {
            throw new BPFAttachError(handle.name, resultAndErr.err());
        }
        attachedPrograms.add(new BPFLink(resultAndErr.result()));
    }

    public void cgroupAttach(ProgramHandle handle, String cgroupName) {
        // tries it four times before giving up
        for (int i = 0; i < 3; i++) {
            try {
                cgroupAttachInternal(handle, cgroupName);
                return;
            } catch (BPFAttachError e) {
                try {
                    Thread.sleep(100);
                } catch (InterruptedException interruptedException) {
                    throw new BPFAttachError(handle.name, "Cgroup not found: " + cgroupName);
                }
            }
        }
        cgroupAttachInternal(handle, cgroupName);
    }

    private MemorySegment allocateTCHookObject(Arena arena, AttachedTCIfIndex tcIfIndex) {
        MemorySegment hook = arena.allocate(bpf_tc_hook.sizeof());
        hook.fill((byte) 0);
        bpf_tc_hook.sz(hook, bpf_tc_hook.sizeof());
        bpf_tc_hook.ifindex(hook, tcIfIndex.ifindex);
        bpf_tc_hook.attach_point(hook, tcIfIndex.ingress ? BPF_TC_INGRESS() : BPF_TC_EGRESS());
        bpf_tc_hook.parent(hook, 0);
        return hook;
    }

    private MemorySegment allocateTCOptsObject(Arena arena, AttachedTCIfIndex tcIfIndex) {
        MemorySegment opts = arena.allocate(bpf_tc_opts.sizeof());
        var progFd = Lib.bpf_program__fd(tcIfIndex.handle.prog());
        if (progFd <= 0) {
            throw new BPFAttachError(tcIfIndex.handle.name, -progFd);
        }
        opts.fill((byte) 0);
        bpf_tc_opts.sz(opts, bpf_tc_opts.sizeof());
        bpf_tc_opts.handle(opts, tcIfIndex.tcHandle);
        bpf_tc_opts.prog_fd(opts, progFd);
        bpf_tc_opts.prog_id(opts, 0);
        bpf_tc_opts.priority(opts, tcIfIndex.priority);
        return opts;
    }

    private void tcDetach(AttachedTCIfIndex tcIfIndex) {
        try (var arena = Arena.ofConfined()) {
            MemorySegment hook = allocateTCHookObject(arena, tcIfIndex);
            MemorySegment opts = allocateTCOptsObject(arena, tcIfIndex);
            // bpf_tc_detach identifies the filter by handle+priority; prog_fd must be 0.
            bpf_tc_opts.prog_fd(opts, 0);
            bpf_tc_opts.prog_id(opts, 0);
            int err = Lib.bpf_tc_detach(hook, opts);
            if (err != 0) {
                throw new BPFError("Detaching " + tcIfIndex.handle.name, err);
            }
        }
    }

    public void detachProgram(BPFLink link) {
        if (!attachedPrograms.contains(link)) {
            throw new IllegalArgumentException("Program not attached");
        }
        if (link.segment.address() == 0) {
            throw new IllegalArgumentException("Improper link");
        }
        Lib.bpf_link__destroy(link.segment);
        attachedPrograms.remove(link);
        var evt = new BPFEvents.ProgramDetach();
        if (evt.isEnabled()) {
            evt.programName = "link@" + Long.toHexString(link.segment.address());
            evt.commit();
        }
    }

    /**
     * Close the program and remove it
     */
    @Override
    public void close() {
        if (closed) {
            return;
        }
        // Snapshot under the synchronized set's monitor — shutdown hooks for
        // cooperating programs run concurrently, so dependents may change
        // between the emptiness check and the error-message construction.
        List<BPFProgram> liveDependents;
        synchronized (dependents) {
            liveDependents = dependents.isEmpty() ? List.of() : new ArrayList<>(dependents);
        }
        if (!liveDependents.isEmpty()) {
            var names = liveDependents.stream()
                    .map(d -> d.getClass().getSimpleName())
                    .sorted()
                    .toList();
            throw new IllegalStateException(
                    "Cannot close " + getClass().getSimpleName() + ": "
                    + liveDependents.size() + " consumer(s) still alive: " + names
                    + ". Close consumers first.");
        }
        closeUnchecked();
    }

    /**
     * Close without checking for live dependents. Used by the JVM-shutdown hook
     * registered in the constructor: at shutdown the producer's and consumer's
     * hooks run concurrently and there's no reliable way to enforce ordering, so
     * we tear down kernel state regardless. End-of-program teardown is what we
     * want; the dependent-check is only useful during normal application
     * lifetime to catch programmer errors.
     */
    private void closeUnchecked() {
        if (closed) {
            return;
        }
        closed = true;
        for (var producer : new HashSet<>(producers)) {
            producer.removeDependent(this);
        }
        producers.clear();
        for (var structOps : attachedStructOps) {
            Lib.bpf_link__destroy(structOps);
        }
        for (var prog : new HashSet<>(attachedPrograms)) {
            detachProgram(prog);
        }
        for (var ifindex : new HashSet<>(attachedXDPIfIndexes)) {
            Lib.bpf_xdp_detach(ifindex.ifindex, ifindex.flags, MemorySegment.NULL);
        }
        for (var tcIfIndex : new HashSet<>(attachedTCIfIndices)) {
            tcDetach(tcIfIndex);
        }
        for (var map : new HashSet<>(attachedMaps)) {
            map.close();
        }
        Lib.bpf_object__close(this.ebpf_object);
        openedFDs.forEach(LibC::close);
        stopStatusServer();
    }

    /**
     * Print the kernel debug trace pipe
     * <p>
     *
     * @see TraceLog#printLoop()
     */
    public void tracePrintLoop() {
        TraceLog.getInstance().printLoop();
    }

    /**
     * Print the kernel debug trace pipe, cleaning the output
     * <p>
     * @see TraceLog#printLoop(boolean)
     */
    public void tracePrintLoopCleaned() {
        TraceLog.getInstance().printLoop(true);
    }

    /**
     * Read from the kernel debug trace pipe and print on stdout.
     *
     * @param format optional function to format the output
     *               <p>
     *               Example
     *               {@snippet *tracePrintLoop(f->f.format("pid {1}, msg = {5}"));
     *}
     */
    public void tracePrintLoop(Function<TraceFields, @Nullable String> format) {
        TraceLog.getInstance().printLoop(format);
    }

    public String readTraceLine() {
        return TraceLog.getInstance().readLine();
    }

    public TraceFields readTraceFields() {
        return TraceLog.getInstance().readFields();
    }


    /**
     * Thrown when a map could not be found
     */
    public static class BPFMapNotFoundError extends BPFError {
        public BPFMapNotFoundError(String name) {
            super("Map not found: " + name);
        }
    }

    /**
     * Get a map descriptor by name
     *
     * @param name the name of the map
     * @return the map descriptor
     * @throws BPFMapNotFoundError if the map cannot be found
     */
    public FileDescriptor getMapDescriptorByName(String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment map = Lib.bpf_object__find_map_by_name(this.ebpf_object, arena.allocateFrom(name));
            if (map == MemorySegment.NULL || map.address() == 0) {
                throw new BPFMapNotFoundError(name);
            }
            return new FileDescriptor(name, map, Lib.bpf_map__fd(map));
        }
    }

    public <T extends BPFMap> T recordMap(T map) {
        attachedMaps.add(map);
        return map;
    }

    /**
     * Get a map by name
     *
     * @param name       the name of the map
     * @param mapCreator function to create the map
     * @param <M>        the type of the map
     * @return the map
     * @throws BPFMapNotFoundError       if the map cannot be found
     * @throws BPFMap.BPFMapTypeMismatch if the type of the map does not match the expected type
     */
    public <M extends BPFMap> M getMapByName(String name, Function<FileDescriptor, M> mapCreator) {
        return recordMap(mapCreator.apply(getMapDescriptorByName(name)));
    }

    // ──────────────────────────────────────────────────────────
    // BPF object pinning
    // ──────────────────────────────────────────────────────────

    /**
     * Pins the named BPF map to the BPF filesystem at the given path.
     *
     * <p>After pinning, the map survives the Java process exit and can be
     * re-opened by another process using {@link #openPinnedMap}.
     *
     * @param mapName the map field name as declared in the {@code @BPF} class
     * @param path    absolute path under the BPF filesystem (e.g. {@code /sys/fs/bpf/mymap})
     * @throws BPFError if pinning fails
     */
    public void pinMap(String mapName, String path) {
        try (Arena arena = Arena.ofConfined()) {
            var fd = getMapDescriptorByName(mapName);
            int ret = Lib_2.bpf_map__pin(fd.map(), arena.allocateFrom(path));
            if (ret != 0) {
                throw new BPFError("Failed to pin map '" + mapName + "' to " + path + ": " + ret);
            }
        }
    }

    /**
     * Pins a {@link BPFLink} (an attached kprobe/uprobe/tracepoint/…) to the BPF
     * filesystem at the given path so it survives the Java process exit.
     *
     * @param link the link returned by one of the {@code attach*} methods
     * @param path absolute path under the BPF filesystem
     * @throws BPFError if pinning fails
     */
    public void pinLink(BPFLink link, String path) {
        try (Arena arena = Arena.ofConfined()) {
            int ret = Lib_2.bpf_link__pin(link.segment(), arena.allocateFrom(path));
            if (ret != 0) {
                throw new BPFError("Failed to pin link to " + path + ": " + ret);
            }
        }
    }

    /**
     * Opens a previously pinned BPF map from the BPF filesystem and wraps it
     * with the supplied creator function.
     *
     * <pre>{@code
     * BPFHashMap<Integer, Long> map = program.openPinnedMap(
     *     "/sys/fs/bpf/mymap",
     *     fd -> new BPFHashMap<>(fd, BPFType.INT32, BPFType.INT64));
     * }</pre>
     *
     * @param path       absolute path to the pinned object
     * @param mapCreator function that wraps the opened FD in a typed map
     * @param <M>        map type
     * @return the opened map
     * @throws BPFError if the path cannot be opened
     */
    public <M extends BPFMap> M openPinnedMap(String path, Function<FileDescriptor, M> mapCreator) {
        try (Arena arena = Arena.ofConfined()) {
            int fd = Lib_2.bpf_obj_get(arena.allocateFrom(path));
            if (fd < 0) {
                throw new BPFError("Failed to open pinned map at " + path + ": " + fd);
            }
            openedFDs.add(fd);
            var fileFd = new FileDescriptor(path, MemorySegment.NULL, fd);
            return recordMap(mapCreator.apply(fileFd));
        }
    }

    // ── Pre-load map pin paths (cross-program sharing) ────────────────────────

    /** Root of the BPF filesystem. Pin paths must live under this. */
    public static final String BPF_FS_ROOT = "/sys/fs/bpf";

    /**
     * Pin paths registered for this program, indexed by map name.
     * Populated by {@link #setMapPinPath(String, String)} between {@code super()}
     * and {@link #finalizeLoad()} in the generated impl-class constructor.
     */
    private final Map<String, String> pinPaths = new LinkedHashMap<>();

    /**
     * Programs that depend on this one (i.e., were loaded with this program as
     * a producer via {@link #load(Class, BPFProgram...)}). Closing this program
     * while {@code dependents} is non-empty throws {@link IllegalStateException}.
     * <p>
     * Uses a synchronized set because shutdown hooks for cooperating programs run
     * concurrently — the producer's close races with the consumer's `removeDependent`.
     */
    private final Set<BPFProgram> dependents = java.util.Collections.synchronizedSet(new HashSet<>());

    /**
     * Producers this program was loaded against. Used to deregister this
     * program as a dependent on close.
     */
    private final Set<BPFProgram> producers = new HashSet<>();

    /**
     * Register a pin path for a BPF map by name <em>before</em>
     * {@link #finalizeLoad()} is called.
     *
     * <p>Must be called from a generated impl-class constructor between
     * {@code super()} (which opens the BPF object) and {@code finalizeLoad()}
     * (which loads it). Calling after load throws {@link IllegalStateException}.
     *
     * <p>If the path already exists in the BPF filesystem and references a
     * compatible map, libbpf reuses it instead of creating a new map — this is
     * the mechanism behind {@code @SharedFrom} cross-program map sharing.
     *
     * @param mapName name of an {@code @BPFMapDefinition} field
     * @param path    absolute path under {@link #BPF_FS_ROOT}
     * @throws IllegalStateException if called after {@link #finalizeLoad()}
     * @throws BPFError              if the map cannot be found, the path is invalid,
     *                               or libbpf rejects the pin path
     */
    protected final void setMapPinPath(String mapName, String path) {
        if (loaded) {
            throw new IllegalStateException(
                    "setMapPinPath('" + mapName + "', '" + path + "') called after finalizeLoad();" +
                    " pin paths must be registered between super() and finalizeLoad()");
        }
        if (path == null || path.isEmpty()) {
            throw new BPFError("Pin path must be a non-empty absolute path under " + BPF_FS_ROOT);
        }
        if (!path.startsWith(BPF_FS_ROOT + "/")) {
            throw new BPFError("Pin path must live under " + BPF_FS_ROOT + "/, got: " + path);
        }
        // Ensure the parent directory exists so libbpf doesn't fail with ENOENT.
        Path parent = Path.of(path).getParent();
        if (parent != null) {
            try {
                Files.createDirectories(parent);
            } catch (IOException e) {
                throw new BPFError("Failed to create pin parent directory " + parent + ": " + e.getMessage());
            }
        }
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment map = Lib.bpf_object__find_map_by_name(this.ebpf_object, arena.allocateFrom(mapName));
            if (map == MemorySegment.NULL || map.address() == 0) {
                throw new BPFMapNotFoundError(mapName);
            }
            int ret = Lib_2.bpf_map__set_pin_path(map, arena.allocateFrom(path));
            if (ret != 0) {
                throw new BPFError("bpf_map__set_pin_path failed for '" + mapName + "' -> "
                        + path + ": " + Util.errnoString(-ret));
            }
        }
        pinPaths.put(mapName, path);
    }

    /**
     * @return the registered pin path for {@code mapName}, or {@code null} if
     *         this program does not pin a map of that name.
     */
    public String getPinPath(String mapName) {
        return pinPaths.get(mapName);
    }

    /** @return names of all maps this program pins. */
    public Set<String> getPinnedMapNames() {
        return Collections.unmodifiableSet(pinPaths.keySet());
    }

    /** Default pin directory for a class — {@link #BPF_FS_ROOT}/{mangled-fqn}. */
    public static String defaultPinDir(Class<? extends BPFProgram> clazz) {
        return BPF_FS_ROOT + "/" + clazz.getName().replace('.', '_').replace('$', '_');
    }

    /** Default pin path for a map of the given name on the given producer class. */
    public static String defaultPinPath(Class<? extends BPFProgram> clazz, String mapName) {
        return defaultPinDir(clazz) + "/" + mapName;
    }

    /**
     * Remove a single pin file at {@code path}. Idempotent — does nothing if the
     * file does not exist.
     */
    public static void unpin(String path) {
        try {
            Files.deleteIfExists(Path.of(path));
        } catch (IOException e) {
            throw new BPFError("Failed to unpin " + path + ": " + e.getMessage());
        }
    }

    /**
     * Remove all pin files (and the pin directory itself) for the given producer
     * class. Idempotent — does nothing if the directory does not exist.
     *
     * <p>Called automatically by the producer's generated constructor before
     * {@code openProgram()} so each run starts fresh — pinning persists past
     * process death and we don't want stale state silently reused across runs.
     */
    public static void unpinAllForClass(Class<? extends BPFProgram> clazz) {
        Path dir = Path.of(defaultPinDir(clazz));
        if (!Files.exists(dir)) return;
        try (var stream = Files.walk(dir)) {
            stream.sorted(Comparator.reverseOrder()).forEach(p -> {
                try { Files.deleteIfExists(p); } catch (IOException ignore) { /* best-effort */ }
            });
        } catch (IOException e) {
            throw new BPFError("Failed to wipe pin dir " + dir + ": " + e.getMessage());
        }
    }

    /**
     * Register {@code dependent} as depending on this program. Closing this
     * program while a dependent is alive throws {@link IllegalStateException}.
     */
    final void addDependent(BPFProgram dependent) {
        dependents.add(dependent);
        dependent.producers.add(this);
    }

    final void removeDependent(BPFProgram dependent) {
        dependents.remove(dependent);
    }

    /**
     * Get a ring buffer by name
     * <p>
     * Keep in mind to regularly call {@link BPFRingBuffer#consumeAndThrow()} to consume the events
     *
     * @param name      the name of the ring buffer
     * @param eventType type of the event
     * @param callback  callback that is called when a new event is received
     * @param <E>       the type of the event
     * @return the ring buffer
     * @throws BPFMapNotFoundError              if the ring buffer cannot be found
     * @throws BPFMap.BPFMapTypeMismatch        if the type of the ring buffer does not match the expected type
     * @throws BPFRingBuffer.BPFRingBufferError if the ring buffer could not be created
     */
    public <E> BPFRingBuffer<E> getRingBufferByName(String name, BPFType<E> eventType,
                                                    BPFRingBuffer.EventCallback<E> callback) {
        return recordMap(getMapByName(name, fd -> new BPFRingBuffer<>(fd, eventType, callback)));
    }

    public <K, V> BPFHashMap<K, V> getHashMapByName(String name, BPFType<K> keyType,
                                                    BPFType<V> valueType) {
        var fd = getMapDescriptorByName(name);
        MapTypeId type = BPFMap.getInfo(fd).type();
        return recordMap(new BPFHashMap<>(fd, type == MapTypeId.LRU_HASH, keyType, valueType));
    }

    private static final HandlerWithErrno<MemorySegment> BPF_MAP__ATTACH_STRUCT_OPS =
            new HandlerWithErrno<>("bpf_map__attach_struct_ops",
                    FunctionDescriptor.of(PanamaUtil.POINTER, PanamaUtil.POINTER));

    public void attachStructOps(String name) {
        var opsDescriptor = getMapDescriptorByName(name);
        if (opsDescriptor == null) {
            throw new BPFMapNotFoundError("Could not find struct ops " + name);
        }

        var res = BPF_MAP__ATTACH_STRUCT_OPS.call(opsDescriptor.map());
        if (res.result() == MemorySegment.NULL && res.hasError()) {
            throw new BPFAttachError("Failed to attach struct ops " + name, res.err());
        }
        attachedStructOps.add(res.result());
    }

    /**
     * Polls data from all ring buffers and consumes if available.
     *
     * @throws BPFRingBufferError if calling the consume method failed,
     *         or if any errors were caught in the call-back of any ring buffer
     */
    public void consumeAndThrow() {
        for (var map : attachedMaps) {
            if (map instanceof BPFRingBuffer) {
                ((BPFRingBuffer<?>)map).consumeAndThrow();
            }
        }
    }

    /**
     * Runs a drain-and-sleep loop until SIGINT (Ctrl-C) or the given wall-clock
     * {@code timeout} elapses, whichever comes first.
     *
     * <p>On each iteration all ring buffers are drained via
     * {@link #consumeAndThrow()}, then the thread sleeps for {@code pollInterval}
     * before the next drain.  When the loop exits (for either reason) the ring
     * buffers are drained one final time so no trailing events are lost.
     *
     * <p>Typical usage in a {@code main} method:
     * <pre>{@code
     *   try (var prog = BPFProgram.load(MyProgram.class)) {
     *       prog.autoAttachPrograms();
     *       prog.runUntilInterrupted(Duration.ofMinutes(5));
     *   }
     * }</pre>
     *
     * @param timeout      maximum wall-clock time to run; {@link Duration#ZERO} or
     *                     negative means run until interrupted only
     * @param pollInterval how long to sleep between ring-buffer drains; defaults
     *                     to 100 ms if null
     */
    public void runUntilInterrupted(Duration timeout, Duration pollInterval) {
        if (pollInterval == null) pollInterval = Duration.ofMillis(100);
        final long deadlineNanos = (timeout == null || timeout.isNegative() || timeout.isZero())
                ? Long.MAX_VALUE
                : System.nanoTime() + timeout.toNanos();

        AtomicBoolean interrupted = new AtomicBoolean(false);
        Thread shutdownHook = new Thread(() -> interrupted.set(true));
        Runtime.getRuntime().addShutdownHook(shutdownHook);
        try {
            final long sleepMs = pollInterval.toMillis();
            while (!interrupted.get() && System.nanoTime() < deadlineNanos) {
                consumeAndThrow();
                try {
                    Thread.sleep(sleepMs);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
            }
        } finally {
            try { Runtime.getRuntime().removeShutdownHook(shutdownHook); } catch (IllegalStateException ignored) {}
            consumeAndThrow();
        }
    }

    /**
     * Runs until SIGINT (Ctrl-C).
     * @see #runUntilInterrupted(Duration, Duration)
     */
    public void runUntilInterrupted() {
        runUntilInterrupted(Duration.ZERO, null);
    }

    /**
     * Runs until SIGINT (Ctrl-C) or {@code timeout} elapses.
     * @see #runUntilInterrupted(Duration, Duration)
     */
    public void runUntilInterrupted(Duration timeout) {
        runUntilInterrupted(timeout, null);
    }

    /**
     * Information about a single BPF program entry point loaded into the kernel.
     *
     * @param name      program name (from SEC or function name)
     * @param fd        kernel file descriptor of the program
     * @param id        kernel-assigned program id (stable as long as the program is loaded)
     * @param mapIds    ids of all maps referenced by this program
     * @param runTimeNs total nanoseconds spent executing this program across all CPUs
     * @param runCount  total number of times this program has been invoked
     */
    public record LoadedProgramInfo(
            String name,
            int fd,
            int id,
            List<Integer> mapIds,
            long runTimeNs,
            long runCount
    ) {}

    /**
     * Returns info about every BPF program entry point in this object as reported
     * by the kernel via {@code bpf_prog_get_info_by_fd}.
     *
     * <p>The returned list is ordered by the order the programs appear in the BPF
     * object (i.e. the order they were declared).
     */
    public List<LoadedProgramInfo> loaded() {
        List<LoadedProgramInfo> result = new ArrayList<>();
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment prog = MemorySegment.NULL;
            while (true) {
                prog = Lib_2.bpf_object__next_program(ebpf_object, prog);
                if (prog == null || MemorySegment.NULL.equals(prog)) break;

                int fd = Lib_2.bpf_program__fd(prog);
                if (fd < 0) continue;

                // Name from libbpf (doesn't need a kernel call)
                String name = PanamaUtil.toString(Lib_2.bpf_program__name(prog));

                // Query kernel for full info
                var info = bpf_prog_info.allocate(arena);
                var infoLen = PanamaUtil.allocateIntRef(arena, (int) info.byteSize());
                int ret = Lib_2.bpf_prog_get_info_by_fd(fd, info, infoLen);
                if (ret < 0) continue;

                int id = bpf_prog_info.id(info);
                long runTimeNs = bpf_prog_info.run_time_ns(info);
                long runCount = bpf_prog_info.run_cnt(info);

                // Collect map IDs: nr_map_ids tells us how many there are, but to retrieve
                // them we need to pass a buffer.  Do a second call with a map_ids buffer.
                int nrMapIds = bpf_prog_info.nr_map_ids(info);
                List<Integer> mapIds = new ArrayList<>(nrMapIds);
                if (nrMapIds > 0) {
                    MemorySegment info2 = bpf_prog_info.allocate(arena);
                    MemorySegment mapIdsBuf = arena.allocate((long) nrMapIds * 4);
                    bpf_prog_info.nr_map_ids(info2, nrMapIds);
                    bpf_prog_info.map_ids(info2, mapIdsBuf.address());
                    MemorySegment infoLen2 = PanamaUtil.allocateIntRef(arena, (int) info2.byteSize());
                    if (Lib_2.bpf_prog_get_info_by_fd(fd, info2, infoLen2) >= 0) {
                        int actual = bpf_prog_info.nr_map_ids(info2);
                        for (int i = 0; i < actual; i++) {
                            mapIds.add(mapIdsBuf.get(JAVA_INT, (long) i * 4));
                        }
                    }
                }

                result.add(new LoadedProgramInfo(name != null ? name : "", fd, id, mapIds, runTimeNs, runCount));
            }
        }
        return result;
    }

    private @Nullable HttpServer statusServer;

    /**
     * Starts an embedded HTTP status server on the given port.
     *
     * <p>Endpoints:
     * <ul>
     *   <li>{@code GET /status} — JSON object with program info and map contents</li>
     *   <li>{@code GET /}       — Simple HTML page rendering the same data</li>
     * </ul>
     *
     * <p>Call {@link #stopStatusServer()} or close the program to stop it.
     *
     * @param port TCP port to listen on
     * @throws IOException if the server could not be started
     */
    public void startStatusServer(int port) throws IOException {
        if (statusServer != null) {
            statusServer.stop(0);
        }
        statusServer = HttpServer.create(new InetSocketAddress(port), 0);
        statusServer.setExecutor(Executors.newSingleThreadExecutor(r -> {
            var t = new Thread(r, "bpf-status-server");
            t.setDaemon(true);
            return t;
        }));
        statusServer.createContext("/status", exchange -> {
            var json = buildStatusJson();
            var bytes = json.getBytes(java.nio.charset.StandardCharsets.UTF_8);
            exchange.getResponseHeaders().set("Content-Type", "application/json; charset=utf-8");
            exchange.sendResponseHeaders(200, bytes.length);
            try (OutputStream out = exchange.getResponseBody()) {
                out.write(bytes);
            }
        });
        statusServer.createContext("/", exchange -> {
            var html = buildStatusHtml();
            var bytes = html.getBytes(java.nio.charset.StandardCharsets.UTF_8);
            exchange.getResponseHeaders().set("Content-Type", "text/html; charset=utf-8");
            exchange.sendResponseHeaders(200, bytes.length);
            try (OutputStream out = exchange.getResponseBody()) {
                out.write(bytes);
            }
        });
        statusServer.start();
    }

    /** Stops the status server started by {@link #startStatusServer(int)}. */
    public void stopStatusServer() {
        if (statusServer != null) {
            statusServer.stop(0);
            statusServer = null;
        }
    }

    private String buildStatusJson() {
        var sb = new StringBuilder();
        sb.append("{");

        // Programs
        sb.append("\"byteCodeHash\":").append(jsonString(byteCodeHash())).append(",");
        sb.append("\"programs\":[");
        var programs = loaded();
        for (int i = 0; i < programs.size(); i++) {
            if (i > 0) sb.append(",");
            var p = programs.get(i);
            sb.append("{");
            sb.append("\"name\":").append(jsonString(p.name())).append(",");
            sb.append("\"id\":").append(p.id()).append(",");
            sb.append("\"fd\":").append(p.fd()).append(",");
            sb.append("\"runTimeNs\":").append(p.runTimeNs()).append(",");
            sb.append("\"runCount\":").append(p.runCount()).append(",");
            sb.append("\"mapIds\":[");
            var mapIds = p.mapIds();
            for (int j = 0; j < mapIds.size(); j++) {
                if (j > 0) sb.append(",");
                sb.append(mapIds.get(j));
            }
            sb.append("]");
            sb.append("}");
        }
        sb.append("],");

        // Maps
        sb.append("\"maps\":[");
        var mapsArr = new ArrayList<>(attachedMaps);
        for (int i = 0; i < mapsArr.size(); i++) {
            if (i > 0) sb.append(",");
            var map = mapsArr.get(i);
            var info = map.getInfo();
            sb.append("{");
            sb.append("\"name\":").append(jsonString(map.getFd().name())).append(",");
            sb.append("\"type\":").append(jsonString(info.type().name())).append(",");
            sb.append("\"maxEntries\":").append(info.maxEntries()).append(",");
            sb.append("\"entries\":");
            if (map instanceof BPFBaseMap<?, ?> baseMap) {
                sb.append("[");
                var entries = new ArrayList<>(baseMap.entrySet());
                for (int j = 0; j < entries.size(); j++) {
                    if (j > 0) sb.append(",");
                    var entry = entries.get(j);
                    sb.append("{\"key\":").append(jsonString(String.valueOf(entry.getKey())));
                    sb.append(",\"value\":").append(jsonString(String.valueOf(entry.getValue())));
                    sb.append("}");
                }
                sb.append("]");
            } else {
                sb.append("null");
            }
            sb.append("}");
        }
        sb.append("]");

        sb.append("}");
        return sb.toString();
    }

    private String buildStatusHtml() {
        var json = buildStatusJson();
        return "<!DOCTYPE html><html><head><title>BPF Status</title>"
                + "<style>body{font-family:monospace;padding:1em}"
                + "table{border-collapse:collapse;margin-bottom:1em}"
                + "td,th{border:1px solid #ccc;padding:4px 8px;text-align:left}"
                + "th{background:#eee}</style></head><body>"
                + "<h1>BPF Program Status</h1>"
                + "<pre id='json'>" + htmlEscape(json) + "</pre>"
                + "<script>var d=JSON.parse(document.getElementById('json').textContent);"
                + "document.body.innerHTML='<h1>BPF Program Status</h1>';"
                + "document.body.innerHTML+='<h2>Programs</h2><table><tr><th>Name</th><th>ID</th>"
                + "<th>Run Count</th><th>Run Time (ms)</th></tr>';"
                + "d.programs.forEach(p=>document.body.innerHTML+='<tr><td>'+p.name+'</td><td>'"
                + "+p.id+'</td><td>'+p.runCount+'</td><td>'+(p.runTimeNs/1e6).toFixed(2)+'</td></tr>');"
                + "document.body.innerHTML+='</table><h2>Maps</h2>';"
                + "d.maps.forEach(m=>{document.body.innerHTML+='<h3>'+m.name+' ('+m.type+')'+'</h3>';"
                + "if(m.entries){document.body.innerHTML+='<table><tr><th>Key</th><th>Value</th></tr>';"
                + "m.entries.forEach(e=>document.body.innerHTML+='<tr><td>'+e.key+'</td><td>'+e.value+'</td></tr>');"
                + "document.body.innerHTML+='</table>';}});"
                + "</script></body></html>";
    }

    private static String jsonString(String s) {
        if (s == null) return "null";
        return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"")
                .replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t") + "\"";
    }

    private static String htmlEscape(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private @Nullable String getDefaultPropertyValue(String name) {
        ArrayDeque<Class<?>> queue = new ArrayDeque<>(List.of(getClass()));
        while (!queue.isEmpty()) {
            var clazz = queue.poll();
            var annotation = clazz.getAnnotation(PropertyDefinitions.class);
            if (annotation != null) {
                for (var prop : annotation.value()) {
                    if (prop.name().equals(name)) {
                        return prop.defaultValue();
                    }
                }
            }
            var prop = clazz.getAnnotation(PropertyDefinition.class);
            if (prop != null && prop.name().equals(name)) {
                return prop.defaultValue();
            }
            queue.addAll(Arrays.asList(clazz.getSuperclass().getInterfaces()));
        }
        return null;
    }

    public @Nullable String getPropertyValue(String name) {
        ArrayDeque<Class<?>> queue = new ArrayDeque<>(List.of(getClass()));
        while (!queue.isEmpty()) {
            var clazz = queue.poll();
            var annotation = clazz.getAnnotation(Properties.class);
            if (annotation != null) {
                for (var prop : annotation.value()) {
                    if (prop.name().equals(name)) {
                        return prop.value();
                    }
                }
            }
            var prop = clazz.getAnnotation(Property.class);
            if (prop != null && prop.name().equals(name)) {
                return prop.value();
            }
            queue.addAll(Arrays.asList(clazz.getInterfaces()));
            if (clazz.getSuperclass() != null) {
                queue.add(clazz.getSuperclass());
            }
        }
        return getDefaultPropertyValue(name);
    }

    public static class BTF {

        private final MemorySegment bpfObject;
        private Map<Integer, BTFType> types = new HashMap<>();

        BTF(MemorySegment bpfObject) {
            this.bpfObject = bpfObject;
        }

        public enum Kind {
            UNKN(0),
            INT(1),
            PTR(2),
            ARRAY(3),
            STRUCT(4),
            UNION(5),
            ENUM(6),
            FWD(7),
            TYPEDEF(8),
            VOLATILE(9),
            CONST(10),
            RESTRICT(11),
            FUNC(12),
            FUNC_PROTO(13),
            VAR(14),
            DATASEC(15),
            FLOAT(16),
            DECL_TAG(17),
            TYPE_TAG(18),
            ENUM64(19);

            private final int value;

            Kind(int value) {
                this.value = value;
            }

            public int value() {
                return value;
            }

            public static Kind fromValue(int value) {
                return values()[value];
            }
        }

        public static class BTFType {

            private static int kind(int info) {
                return (info >> 24) & 0xff;
            }

            private static int vlen(int info) {
                return info & 0xffff;
            }

            private final BTF btf;
            private final MemorySegment typeObj;
            private final Kind kind;
            private final String name;

            public BTFType(BTF btf, MemorySegment typeObj) {
                this.btf = btf;
                this.typeObj = typeObj;
                this.kind = Kind.fromValue(kind(btf_type.info(typeObj)));
                this.name = PanamaUtil.toString(Lib.btf__name_by_offset(btf.bpfObject, btf_type.name_off(typeObj)));
            }

            Kind kind() {
                return kind;
            }

            String name() {
                return name;
            }

            int memberCount() {
                return vlen(btf_type.info(typeObj));
            }

            record VariableSectionInfo(BTFType type, int offset, int size) {
                String name() {
                    return type.name;
                }
            }

            List<VariableSectionInfo> getVariableSectionInfos() {
                // in c code:
                // btf_var_secinfo *ptr = (struct btf_var_secinfo *)(type + 1);
                // assume that btf_var_secinfo and btf_type are 4 byte aligned
                var infos = typeObj.address() + btf_type.sizeof();
                return IntStream.range(0, memberCount()).mapToObj(i -> {
                    var elem = MemorySegment.ofAddress(infos + i * btf_var_secinfo.sizeof()).reinterpret(btf_var_secinfo.sizeof());
                    return new VariableSectionInfo(btf.getTypeById(btf_var_secinfo.type(elem)), btf_var_secinfo.offset(elem), btf_var_secinfo.size(elem));
                }).toList();
            }
        }

        int findIdByName(String name) {
            try (Arena arena = Arena.ofConfined()) {
                int id = Lib.btf__find_by_name(bpfObject, arena.allocateFrom(name));
                if (id < 0) {
                    throw new BPFError("Failed to find BTF by name: " + name);
                }
                return id;
            }
        }

        BTFType getTypeById(int id) {
            return types.computeIfAbsent(id, i -> {
                try (Arena arena = Arena.ofConfined()) {
                    MemorySegment segment = Lib.btf__type_by_id(bpfObject, id);
                    if (segment == MemorySegment.NULL) {
                        throw new BPFError("Failed to get BTF type by id: " + id);
                    }
                    return new BTFType(this, segment);
                }
            });
        }

        BTFType findTypeByName(String name) {
            return getTypeById(findIdByName(name));
        }
    }

    private BTF btf = null;

    public BTF getBTF() {
        if (btf == null) {
            var ret = Lib.bpf_object__btf(this.ebpf_object);
            if (Lib.libbpf_get_error(ret) != 0) {
                throw new BPFError("Failed to get BTF");
            }
            btf = new BTF(ret);
        }
        return btf;
    }
}