package me.bechberger.ebpf.annotations.bpf;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a {@link BuiltinBPFFunction} stub as a kernel BPF kfunc — a function
 * exported via {@code BTF_KFUNCS_START}/{@code BTF_ID_FLAGS} on the kernel side
 * and tagged with {@code DECL_TAG "bpf_kfunc"} in {@code vmlinux} BTF.
 *
 * <p>kfuncs differ from regular BPF helpers (the {@code BPF_FUNC_*} table) in
 * that they need an explicit C forward declaration with the {@code __ksym}
 * attribute so libbpf can resolve them at load time. The compiler plugin
 * collects all {@link KFunc}-annotated methods that are reachable from the
 * compiled program and emits {@code __ksym} decls in the program prologue.
 *
 * <p>Generated by {@code bpf-gen} from {@code DECL_TAG "bpf_kfunc"} entries —
 * do not hand-apply unless you are extending {@code BpfDefinitions} with a
 * custom kfunc the generator did not pick up.
 *
 * @param signature the full C forward declaration (excluding {@code __ksym}
 *                  and trailing semicolon) — e.g. {@code "struct bpf_cpumask
 *                  *bpf_cpumask_create(void)"}. Generator emits this from BTF.
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface KFunc {
    /**
     * C forward declaration of the kfunc, without the {@code __ksym} suffix
     * or trailing semicolon. The compiler plugin appends {@code __ksym;}
     * when emitting the decl in the program prologue.
     */
    String signature() default "";
}
