package me.bechberger.ebpf.bpf.features;

import org.jetbrains.annotations.Nullable;

/** BPF attach types. Values match {@code uapi/linux/bpf.h} enum bpf_attach_type. */
public enum BPFAttachType {
    CGROUP_INET_INGRESS(0), CGROUP_INET_EGRESS(1), CGROUP_INET_SOCK_CREATE(2),
    CGROUP_SOCK_OPS(3), SK_SKB_STREAM_PARSER(4), SK_SKB_STREAM_VERDICT(5),
    CGROUP_DEVICE(6), SK_MSG_VERDICT(7), CGROUP_INET4_BIND(8),
    CGROUP_INET6_BIND(9), CGROUP_INET4_CONNECT(10), CGROUP_INET6_CONNECT(11),
    CGROUP_INET4_POST_BIND(12), CGROUP_INET6_POST_BIND(13),
    CGROUP_UDP4_SENDMSG(14), CGROUP_UDP6_SENDMSG(15), LIRC_MODE2(16),
    FLOW_DISSECTOR(17), CGROUP_SYSCTL(18), CGROUP_UDP4_RECVMSG(19),
    CGROUP_UDP6_RECVMSG(20), CGROUP_GETSOCKOPT(21), CGROUP_SETSOCKOPT(22),
    TRACE_RAW_TP(23), TRACE_FENTRY(24), TRACE_FEXIT(25), MODIFY_RETURN(26),
    LSM_MAC(27), TRACE_ITER(28), CGROUP_INET4_GETPEERNAME(29),
    CGROUP_INET6_GETPEERNAME(30), CGROUP_INET4_GETSOCKNAME(31),
    CGROUP_INET6_GETSOCKNAME(32), XDP_DEVMAP(33), CGROUP_INET_SOCK_RELEASE(34),
    XDP_CPUMAP(35), SK_LOOKUP(36), XDP(37), SK_SKB_VERDICT(38),
    SK_REUSEPORT_SELECT(39), SK_REUSEPORT_SELECT_OR_MIGRATE(40),
    PERF_EVENT(41), TRACE_KPROBE_MULTI(42), LSM_CGROUP(43), STRUCT_OPS(44),
    NETFILTER(45), TCX_INGRESS(46), TCX_EGRESS(47),
    TRACE_UPROBE_MULTI(48), CGROUP_UNIX_CONNECT(49), CGROUP_UNIX_SENDMSG(50),
    CGROUP_UNIX_RECVMSG(51), CGROUP_UNIX_GETPEERNAME(52),
    CGROUP_UNIX_GETSOCKNAME(53), NETKIT_PRIMARY(54), NETKIT_PEER(55);

    private final int id;
    BPFAttachType(int id) { this.id = id; }
    public int id() { return id; }

    public static @Nullable BPFAttachType fromId(int id) {
        for (var t : values()) if (t.id == id) return t;
        return null;
    }
}
