package me.bechberger.ebpf.bpf.compiler;

import com.sun.source.tree.MethodInvocationTree;
import com.sun.source.tree.MethodTree;
import com.sun.source.util.TreeScanner;
import com.sun.tools.javac.code.Symbol.MethodSymbol;
import me.bechberger.ebpf.annotations.bpf.KFunc;
import me.bechberger.ebpf.bpf.compiler.CompilerPlugin.TypedTreePath;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Walks a {@code @BPFFunction} method body, finds calls to methods annotated
 * with {@link KFunc}, and records their C signatures in a per-method map keyed
 * by kfunc name. The compiler plugin aggregates these across all methods of
 * a program and emits one {@code __ksym} forward declaration per unique kfunc
 * in the program prologue.
 *
 * <p>The signature is the C declaration carried on the {@code @KFunc} stub
 * (generated by {@code bpf-gen} from BTF). Re-emitting it as
 * {@code <signature> __ksym;} is what libbpf needs to relocate the kfunc at
 * load time.
 */
public class KFuncCollectPass {

    private final CompilerPlugin compilerPlugin;
    private final TypedTreePath<MethodTree> methodPath;
    private final Map<String, String> calledKFuncs = new LinkedHashMap<>();

    public KFuncCollectPass(CompilerPlugin compilerPlugin, TypedTreePath<MethodTree> methodPath) {
        this.compilerPlugin = compilerPlugin;
        this.methodPath = methodPath;
    }

    public Map<String, String> analyze() {
        var method = methodPath.leaf();
        var body = method.getBody();
        if (body == null) return calledKFuncs;

        new TreeScanner<Void, Void>() {
            @Override
            public Void visitMethodInvocation(MethodInvocationTree node, Void p) {
                var sym = methodSymbol(node);
                if (sym != null) {
                    var kfunc = compilerPlugin.getAnnotationOfMethodOrSuper(sym, KFunc.class);
                    if (kfunc != null) {
                        var sig = kfunc.signature();
                        if (sig != null && !sig.isEmpty()) {
                            calledKFuncs.putIfAbsent(sym.getSimpleName().toString(), sig);
                        }
                    }
                }
                return super.visitMethodInvocation(node, p);
            }
        }.scan(body, null);
        return calledKFuncs;
    }

    private static MethodSymbol methodSymbol(MethodInvocationTree call) {
        try {
            return switch (call.getMethodSelect()) {
                case com.sun.tools.javac.tree.JCTree.JCFieldAccess fa -> (MethodSymbol) fa.sym;
                case com.sun.tools.javac.tree.JCTree.JCIdent id -> (MethodSymbol) id.sym;
                default -> null;
            };
        } catch (ClassCastException e) {
            return null;
        }
    }
}
