package me.bechberger.ebpf.bpf.compiler;

import com.sun.source.tree.MethodInvocationTree;
import com.sun.source.tree.MethodTree;
import com.sun.source.util.TreeScanner;
import com.sun.tools.javac.code.Symbol.MethodSymbol;
import me.bechberger.ebpf.bpf.compiler.CompilerPlugin.TypedTreePath;

import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.ExecutableElement;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Walks a {@code @BPFFunction} method body, finds calls to methods annotated
 * with {@link me.bechberger.ebpf.annotations.bpf.KFunc}, and records their C
 * signatures in a per-method map keyed by kfunc name. The compiler plugin
 * aggregates these across all methods of a program and emits one
 * {@code __ksym} forward declaration per unique kfunc in the program prologue.
 *
 * <p>The signature is the C declaration carried on the {@code @KFunc} stub
 * (generated by {@code bpf-gen} from BTF). Re-emitting it as
 * {@code <signature> __ksym;} is what libbpf needs to relocate the kfunc at
 * load time.
 */
public class KFuncCollectPass {

    private static final String KFUNC_ANNOTATION_NAME =
            "me.bechberger.ebpf.annotations.bpf.KFunc";

    private final TypedTreePath<MethodTree> methodPath;
    private final Map<String, String> calledKFuncs = new LinkedHashMap<>();

    public KFuncCollectPass(CompilerPlugin compilerPlugin, TypedTreePath<MethodTree> methodPath) {
        this.methodPath = methodPath;
    }

    public Map<String, String> analyze() {
        var method = methodPath.leaf();
        var body = method.getBody();
        if (body == null) return calledKFuncs;

        new TreeScanner<Void, Void>() {
            @Override
            public Void visitMethodInvocation(MethodInvocationTree node, Void p) {
                var sym = methodSymbol(node);
                if (sym != null) {
                    String sig = getKFuncSignature(sym);
                    if (sig != null && !sig.isEmpty()) {
                        calledKFuncs.putIfAbsent(sym.getSimpleName().toString(), sig);
                    }
                }
                return super.visitMethodInvocation(node, p);
            }
        }.scan(body, null);
        return calledKFuncs;
    }

    /**
     * Extracts the {@code @KFunc.signature()} value from a method symbol.
     *
     * <p>{@code sym.getAnnotation(KFunc.class)} works for both source-compiled
     * symbols and for class-file symbols loaded from jars: javac's
     * {@code ClassReader} populates method annotations when the enclosing class
     * is completed, and by the time the {@code ANALYZE} phase runs (where our
     * plugin fires) the {@code Annotate} queue has already been flushed.
     *
     * <p>The annotation-mirror fallback handles the edge case where the
     * annotation type is loaded by a different classloader.
     */
    private String getKFuncSignature(MethodSymbol sym) {
        var kfunc = sym.getAnnotation(me.bechberger.ebpf.annotations.bpf.KFunc.class);
        if (kfunc != null) {
            String sig = kfunc.signature();
            return (sig != null && !sig.isEmpty()) ? sig : "";
        }

        // Fallback: annotation-mirror scan by name (handles classloader mismatch)
        List<? extends AnnotationMirror> mirrors;
        try {
            mirrors = sym.getAnnotationMirrors();
        } catch (Exception ignored) {
            return null;
        }
        for (AnnotationMirror mirror : mirrors) {
            if (mirror.getAnnotationType().toString().equals(KFUNC_ANNOTATION_NAME)) {
                for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry
                        : mirror.getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().toString().equals("signature")) {
                        Object val = entry.getValue().getValue();
                        return val != null ? val.toString() : null;
                    }
                }
                return "";
            }
        }
        return null;
    }

    private static MethodSymbol methodSymbol(MethodInvocationTree call) {
        try {
            return switch (call.getMethodSelect()) {
                case com.sun.tools.javac.tree.JCTree.JCFieldAccess fa -> (MethodSymbol) fa.sym;
                case com.sun.tools.javac.tree.JCTree.JCIdent id -> (MethodSymbol) id.sym;
                default -> null;
            };
        } catch (ClassCastException e) {
            return null;
        }
    }
}
